# Generated by Django 6.0.5 on 2026-05-24 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_group_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_link', to='chat.group'),
        ),
        migrations.AddField(
            model_name='group',
            name='chat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_link', to='chat.chat'),
        ),
    ]
